#########################
# Schema validation test bed
# Also, using _shared
#########################

port: 5042

# threading related stuff
threading:
  min: 4
  max : 8
  timeout: 30000

# path mapping
routes:
  post:
    /person: _/create_person.zm
  get:
    /person/:personId : _/fetch_person.zm

